areas:
  1:
    home:
      x: 1.7
      y: 4.575
      yaw: 0.0
      
    corridor:
      width: 0.8  

  2:
    home:
      x: 1.7
      y: 5.65
      yaw: 0.0

    corridor:
      width: 0.8  
  3:
    home:
      x: 1.7
      y: 6.75
      yaw: 0.0
      
    corridor:
      width: 0.8  
